server:
  servlet:
     context-path: /allarmeteo
    
    
spring:
  application:
    name: AllarMeteo
  profiles:
    active: dev

######################################################
############## Allarmeteo PROPERTIES #################
######################################################

