spring:
  datasource:
    url: jdbc:mysql://localhost:3306/allarmeteo
    username: allarmeteo
    password: allarmeteo
    driver-class-name: com.mysql.cj.jdbc.Driver
  
######################################################
############## Allarmeteo PROPERTIES #################
###################################################### 
