spring:
  datasource:
    url: jdbc:mysql://localhost:3306/allarmeteo
    username: allarmeteo
    password: allarmeteo
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC+1

######################################################
############## Allarmeteo PROPERTIES #################
######################################################
